# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'

- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'

- task: CmdLine@2
  inputs:
    script: |
      docker build -t sai-spring-boot .
      docker tag sai-spring-boot:latest 872154951115.dkr.ecr.us-east-1.amazonaws.com/sai-spring-boot:latest

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'sai.p-aws'
    regionName: 'us-east-1'
    imageSource: 'imagename'
    sourceImageName: '872154951115.dkr.ecr.us-east-1.amazonaws.com/sai-spring-boot'
    repositoryName: 'sai-spring-boot'